test_vectors/README.md
I forgot to update the documentation when I removed a fixed value from the tree math tests.
=> Align documentation of tree math test with the file

interop/Makefile, interop/README.md, interop/config.json, interop/cpp-mock-client/CMakeLists.txt, interop/cpp-mock-client/Makefile, interop/cpp-mock-client/mock_client.cpp, interop/go-mock-client/main.go, interop/rust-mock-client/Cargo.lock, interop/rust-mock-client/Cargo.toml, interop/rust-mock-client/src/main.rs, interop/test-runner/main.go
Couple of minor changes here:
* On the MLS client (gRPC server) side, enables command line arguments to specify what port the client runs on
* On the test runner (gRPC client) side, enables the test runner to connect to multiple clients, specified in a JSON config file
This sets the stage for then doing testing across the connected clients.
=> Enable port variation and connection to multiple clients

interop/config.json, interop/cpp-mock-client/Makefile, interop/cpp-mock-client/mock_client.cpp, interop/go-mock-client/main.go, interop/proto/mls_client.proto, interop/rust-mock-client/src/main.rs, interop/test-runner/main.go, test-vectors.md
This PR adds support for the full suite of test vectors across the proto file and client stubs.  The test runner can now also be configured to run test vector interop tests across clients, including ciphersuite compatibility.
=> Full suite of test vectors

.gitignore, test-vectors.md
This is the result of the discussion in https://github.com/mlswg/mls-implementations/issues/32
and changes tree math and encryption test vectors accordingly.
Note that the representation section currently only applies to these two sections.
fixes #32
=> update treemath and encryption test vector description

test-vectors.md
Looking into implementing the changes in #33, I noticed that we can consolidate the logic in the encryption test vectors a bit more, and increase coverage to cover both handshake and application encryption (which is currently ambiguous).
=> Test handshake and application encryption

interop/cpp-mock-client/mock_client.cpp, interop/go-mock-client/main.go, interop/proto/mls_client.proto, interop/rust-mock-client/src/main.rs, test-harness.md
This PR extends the definend gRPC interface to cover all the methods described in `test-harness.md`, and adds stub methods to the mock clients.
=> Complete gRPC definitions

interop/config.json, interop/cpp-mock-client/mock_client.cpp, interop/go-mock-client/main.go, interop/proto/mls_client.proto, interop/rust-mock-client/src/main.rs, interop/test-runner/main.go
This PR implements interop methods to test "external join", via PublicGroupState.
=> Add external join

interop/config.json, interop/cpp-mock-client/mock_client.cpp, interop/go-mock-client/main.go, interop/proto/mls_client.proto, interop/rust-mock-client/src/main.rs, interop/test-runner/main.go
This PR implements a facility for specifying interop test scenarios, which are then run across all combinations of:
* Assignments of MLS client stacks to actors in the scenario
* Ciphersuites
* Handshake encrypted / not
A basic two-member join scenario is provided in `config.json` and there required actions are implemented in the test runner and the clients.  This scenario works with the test clients, and also with the [corresponding branch of `mlspp`](https://github.com/cisco/mlspp/pull/178).
=> Add interop test scripts

test-vectors.md
Thanks to @kkohbrok we finished the treekem test vector in OpenMLS but had to change it slightly. It's on this [branch](https://github.com/openmls/openmls/tree/franziskus/kat-tree-kem).
* We need the leaf secret because in some cases the path secret is not enough (in case the two nodes are siblings).
* We added the group context to not always use an empty one.
* I clarified that the exclusion list (list of new leaves) is empty.
@bifurcation what do you think?
=> Update treekem test-vectors

test-vectors.md
This requires valid signatures on messages.
Shall we also require valid MAC values if present?
=> Require valid message signatures

test-vectors.md
We need the credential here now because OpenMLS will enforce signature verification.
I also think it generally makes sense to verify the signature as well as the tags here.
=> Add credential to transcript test vector

interop/test-runner/main.go
Increase the timeout for clients to respond to test runner queries.
=> Increase timeout

test-vectors.md
The change in https://github.com/mlswg/mls-protocol/pull/490 is not noticeable with this test vector because only a single PSK is being used.
The KAT should instead take an array of PSKs.
=> make psk_secret an array in key_schedule kat

interop/config.json
External commits need to be handled differently from commits.  For example, they cannot be encrypted, even if other commits are.  The current external join test script uses `handleCommit` where it should use `handleExternalCommit`.
=> Use handleExternalCommit instead of handleCommit

implementation_list.md
Moves a couple of abandoned ones below the line, and adds the Wickr implementation.
@TWal should we add an entry here for your implementation?  Doesn't matter if you have a public repo, just trying to document what exists.
=> Update list of implementations

test-vectors.md
The test vectors only show a single JSON object, but the file has an array of them.  We should have the example JSON  correspond to the file.
=> Clarify tree math test multiplicity

test-vectors.md
This way we don't have to show each example as an array.  The only one for which the array framing doesn't really make sense is the messages test vector, which doesn't depend on the ciphersuite.  We can either special-case that or just make it a one-element array.
=> State that test vector files are an array

test-vectors.md
MLS has several basic crypto functions that make small modifications to the underlying primitives, usually in the interest of domain separation.  This PR adds a test vector type to verify that these functions are correctly implemented, which should help isolate errors in higher-level tests.
Fixes #64 
Depends on #69
=> Add a Crypto Basics test vector

interop/config.json, interop/cpp-mock-client/mock_client.cpp, interop/go-mock-client/main.go, interop/proto/mls_client.proto, interop/rust-mock-client/src/main.rs, interop/test-runner/main.go
Instead of manually passing test vectors from one stack to another via gRPC, we have focused more recently on developing a single suite of test vectors for the protocol.  This PR removes the test vector generate/verify RPCs from the gRPC interface and strips the relevant code from the mock clients and test runner.
=> Remove test vector functions from gRPC interface

test-vectors.md
The confirmation tag is no longer used and can be arbitrary.
=> Remove mentions of confirmation tag from message protection vector

interop/proto/mls_client.proto, interop/test-runner/main.go
Removes are handled by actor identities, which now have to be the same as their MLS basic credentials.
=> Fix removes

go.mod, interop/config.json, interop/cpp-mock-client/mock_client.cpp, interop/go-mock-client/main.go, interop/proto/mls_client.proto, interop/rust-mock-client/src/main.rs, interop/test-runner/main.go
This PR makes a few changes to the Commit RPCs:
* Removes the `HandleExternalCommit` RPC, since all the known stacks use the same API as for normal commits
* Removes the details from `CommitResponse` and `HandleCommitResponse`, since they were unused
* Adds  an `epoch_authenticator` field to `CommitResponse` and `HandleCommitResponse` so that the test runner can quickly check agreement without an extra RPC.
And then implements it in the three mock clients.
=> Clean up Commit RPCs

go.mod, interop/config.json, interop/test-runner/main.go
This PR updates how the test runnier is configured to be more usable:
* Instead of configuring clients in `config.json`, they are provided as command-line options
* A new `-random` option is provided that causes a random selection of clients to be used
* A new `-suite` option is provided that causes tests to only be run for a single ciphersuite
* New `-public` and `-private` options are provided that cause tests to be run with only PublicMessage/PrivateMessage
This should enable us to have more durable `config.json` files that capture different sets of interop tests, and then run those scenarios against various collections of clients.
=> Update test runner config to be more usable

interop/config.json, interop/proto/mls_client.proto, interop/test-runner/main.go
This PR adds a `fullCommit` action to the test runner, which combines the `commit`, `handlePendingCommit`, `handleCommit`, and `joinGroup`.  The motivation here was to remove the need for `CommitResponse.EpochAuthenticator`, which could be challenging for stacks to produce if they haven't moved into the new state.  Just removing would introduce some ambiguity about how to verify that all the member agree on the epoch authenticator; the approach here keeps the epoch authenticator as local state across the individual steps.
Combining these steps also makes the scripts more terse, of course.
Note that with this, the only reason to keep `handleCommit` is to be able to test the case where a member creates a commit, but then another commit gets applied.  We could probably safely delete the …
=> Add a 'fullCommit' action

interop/test-runner/main.go
The join request was sent to some random actor instead of the joiner.
=> Fix bug in full commit action

go.mod, interop/active_to_passive.js, interop/configs/welcome_join.json, interop/proto/mls_client.proto, interop/test-runner/main.go
This PR adds a config file `welcome_join.json` that covers join-by-welcome cases.  It also adds some gRPC mechanism that is necessary to generate the required cases:
* Adding `force_path` and `external_tree` fields to CommitRequest, and a `ratchet_tree` field on CommitResponse
* Adding an `installExternalPSK` action that generates a PSK and installs it on clients
* Updating the active-to-passive script to capture PSKs and external trees
I have verified that this works with [my working branch of MLSpp](https://github.com/cisco/mlspp/tree/welcome-config), in the sense that (a) MLSpp interoperates with itself via gRPC, and (b) the generated passive test vector passes.
Depends on #128, should probably not be reviewed until that is merged and this PR is rebased.
=> Join-by-Welcome active tests and supporting API/logic

interop/proto/mls_client.proto, interop/test-runner/main.go
* Renames PublicGroupState to GroupInfo
* Adds options to ExternalJoinRequest to signal:
* Adding PSKs
* Removing a former appearance (with the same identity)
* Adds a composite `externalJoin` action:
* Fetches a GroupInfo from the `actor`
* Has the `joiner` use the GroupInfo to make an external Commit
* Sends the Commit to the `actor` and other `members`
=> External Commit scenarios and related gRPC/logic

go.mod, interop/configs/application.json, interop/proto/mls_client.proto, interop/test-runner/main.go
Tests three scenarios:
* Unprotect in the same order as protect
* Out-of-order unprotect within an epoch
* Out-of-order unprotect across epochs
Also, updates the RPCs to exercise `MLSCiphertext.authenticated_data`.
=> Add application data protection tests

go.mod, interop/configs/reinit.json, interop/proto/mls_client.proto, interop/test-runner/main.go
This PR adds RPCs to do ReInit functions, and a test config to drive it.  Draft for now because I have not implemented the new RPCs or run the scripts (at least the test runner builds, though!).
=> Support Reinit in gRPC-based tests

interop/configs/external_proposals.json, interop/proto/mls_client.proto, interop/test-runner/main.go
* Complete the proposal types in `external_proposals.json`; GCE, resumption PSK and reinit were added.
* Extend the reinit action to allow using an external reint proposal created in a previous step.
* `ChangeCipherSuite` and `NewGroupID` functions are copied without changing the functionality.
=> Add support for reinit by external proposals. Add remaining external proposal types to the config.

interop/test-runner/main.go
This is useful to run the test in CI (returning 1 causes the CI to fail) and check interoperability with self.
=> Log test failure as error

interop/proto/mls_client.proto, interop/test-runner/main.go
Currently, the script runner tells clients under test to allocate resources (CreateKeyPackage, CreateGroup, etc.), but never tells them when those resources are no longer needed.  This PR adds a `Free()` RPC to let the client know that the resources for the test are no longer needed, and calls that RPC at the end of a script run.  Only the final state of each client is cleaned up, under the theory that (a) clients can clean up prior states as they change epochs and (b) join resources can be cleaned up once the member joins the group.
=> Add a Free RPC and clean up after a script run

test-vectors.md
Consider the following tree:
```
R
______|______
/             \
_               _
__|__           __|__
/     \         /     \
_       _       _       _
/ \     / \     / \     / \
A   _   _   _   _   _   _   H
```
In a test where H is removed, several implementations could have differing `candidate_tree_after` while having the same `tree_after`:
For example, if the implementation removes but forget to truncate, we would have the following tree:
```
_
______|______
/             \
_               _
__|__           __|__
/     \         /     \
_       _       _       _
/ \     / \     / \     / \
A   _   _   _   _   _   _   _
```
Or if the implementation truncate after removing, but only one level, the tree could look like this:
```
_      
__|__    
/     \   
_       _  
/ \     / \ …
```
=> Add tree hash inside Tree Operations test vector

docker/Dockerfile.mlspp, docker/Dockerfile.openmls, docker/Dockerfile.test-runner, docker/README.md, docker/docker-compose.yml
In our interop call today, we agreed that it would be helpful to add some Docker tooling to let people do interop testing more easily.  This PR adds Dockerfiles for the test runner and for MLSpp, with the idea that this should allow other folks to send PRs adding their stacks.
Inspired by the [OpenMLS docker tooling](https://github.com/openmls/openmls/tree/main/interop_client/docker).
=> Add Docker-based interop testing

implementation_list.md
This adds my Kotlin implementation of MLS to the implementations list.
The RFC implementation is mostly complete as of today, there are only few minor details missing, such as the Deletion Schedule, which are anyway more of a responsibility of the implementation.
I will implement the Test Harness for interop testing in the near future, but the library is already passing all test vectors.
=> Add mls-kotlin to the implementations list
